In [9]:
import numpy as np
import scipy.io as sio

### Load data from .mat file

In [10]:
mat_contents = sio.loadmat('ash85_data.mat') # ash85_data
data1 = mat_contents['x']

### Print the format of the data: compressed sparse column format(csc)

In [11]:
data1.shape

(85, 85)

### Return a dense ndarray representation of this matrix.

In [12]:
A = data1.todense() # or todense()
print(A.shape)
print(A)

(85, 85)
[[1. 1. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]]


In [13]:
from scipy.linalg import lu_factor, lu_solve
# Task 1: LU factorization
LU,P = lu_factor(A)
print(LU)
print("---------------------------------------------------------------------------------------------")
print(P)
print("-----------------------------------------------------------------------------------------------")
# define a right hand vector b with all ones
B =[1]*85
x = lu_solve((LU, P), B)
print(x)
# use lu_factor and lu_solve to solve Ax=b for both inputs
# solve for ash85_data



[[ 1.          1.          0.         ...  0.          0.
   0.        ]
 [ 0.          1.          1.         ...  0.          0.
   0.        ]
 [ 1.          0.          1.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  1.44838616  0.71503344
   0.970631  ]
 [ 0.          0.          0.         ...  0.16000803  0.5735796
   0.04416784]
 [ 0.          0.          0.         ...  0.82212407  0.36926846
  -1.3339167 ]]
---------------------------------------------------------------------------------------------
[ 0  2  2  3  5  5  7  7  8  9 13 13 12 21 16 15 17 17 19 20 20 22 46 24
 24 26 26 28 38 41 42 63 62 34 37 64 38 37 65 47 40 70 50 51 64 47 70 48
 56 50 60 63 52 55 82 55 57 64 58 60 72 73 82 68 65 66 67 70 69 82 84 71
 75 74 74 76 84 77 79 80 81 82 83 84 84]
-----------------------------------------------------------------------------------------------
[ 0.75216479  0.3912359  -0.44870113  2.89228549  0.79847809 -0.46129625
 -2.192731

In [14]:
# Task 2: verify the correctness of your solutions. 
# In the verification, you can use 
# numpy.allclose function that allows some tolerance
np.allclose(np.dot(A,x),B)

True